<?xml version="1.0" encoding="utf-8"?><Database Name="UaFootball" Class="UaFootball_DBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=UaFootball;User ID=UaFootball" SettingsObjectName="UaFDatabase.Properties.Settings" SettingsPropertyName="UaFootballConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Cities" Member="Cities">
    <Type Name="City">
      <Column Name="City_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="City_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Country_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="City_Club" Member="Clubs" ThisKey="City_ID" OtherKey="City_ID" Type="Club" />
      <Association Name="City_Stadium" Member="Stadiums" ThisKey="City_ID" OtherKey="City_Id" Type="Stadium" />
      <Association Name="Country_City" Member="Country" ThisKey="Country_ID" OtherKey="Country_ID" Type="Country" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Countries" Member="Countries">
    <Type Name="Country">
      <Column Name="Country_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Country_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Country_Code" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="FIFAAssociation_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Country_City" Member="Cities" ThisKey="Country_ID" OtherKey="Country_ID" Type="City" />
      <Association Name="Country_NationalTeam" Member="NationalTeams" ThisKey="Country_ID" OtherKey="Country_Id" Type="NationalTeam" />
      <Association Name="Country_Referee" Member="Referees" ThisKey="Country_ID" OtherKey="Country_Id" Type="Referee" />
      <Association Name="Country_Player" Member="Players" ThisKey="Country_ID" OtherKey="Country_Id" Type="Player" />
      <Association Name="Country_Coach" Member="Coaches" ThisKey="Country_ID" OtherKey="CountryId" Type="Coach" />
      <Association Name="FIFAAssociation_Country" Member="FIFAAssociation" ThisKey="FIFAAssociation_ID" OtherKey="FIFAAssociation_ID" Type="FIFAAssociation" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Clubs" Member="Clubs">
    <Type Name="Club">
      <Column Name="Club_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Club_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Display_Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Logo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Year_Found" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="City_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Club_Match" Member="Matches" ThisKey="Club_ID" OtherKey="HomeClub_Id" Type="Match" />
      <Association Name="Club_Match1" Member="Matches1" ThisKey="Club_ID" OtherKey="AwayClub_Id" Type="Match" />
      <Association Name="Club_MultimediaTag" Member="MultimediaTags" ThisKey="Club_ID" OtherKey="Club_ID" Type="MultimediaTag" />
      <Association Name="City_Club" Member="City" ThisKey="City_ID" OtherKey="City_ID" Type="City" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PlayerPositions" Member="PlayerPositions">
    <Type Name="PlayerPosition">
      <Column Name="PlayerPosition_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Player_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Line_Cd" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Wing_Cd" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="Player_PlayerPosition" Member="Player" ThisKey="Player_Id" OtherKey="Player_Id" Type="Player" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NationalTeams" Member="NationalTeams">
    <Type Name="NationalTeam">
      <Column Name="NationalTeam_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Country_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Logo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NationalTeamType_Cd" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Association Name="NationalTeam_Match" Member="Matches" ThisKey="NationalTeam_Id" OtherKey="HomeNationalTeam_Id" Type="Match" />
      <Association Name="NationalTeam_Match1" Member="Matches1" ThisKey="NationalTeam_Id" OtherKey="AwayNationalTeam_Id" Type="Match" />
      <Association Name="NationalTeam_MultimediaTag" Member="MultimediaTags" ThisKey="NationalTeam_Id" OtherKey="NationalTeam_ID" Type="MultimediaTag" />
      <Association Name="Country_NationalTeam" Member="Country" ThisKey="Country_Id" OtherKey="Country_ID" Type="Country" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CompetitionStages" Member="CompetitionStages">
    <Type Name="CompetitionStage">
      <Column Name="CompetitionStage_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Competition_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CompetitionStage_Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="CompetitionStage_Match" Member="Matches" ThisKey="CompetitionStage_ID" OtherKey="CompetitionStage_Id" Type="Match" />
    </Type>
  </Table>
  <Table Name="dbo.Referees" Member="Referees">
    <Type Name="Referee">
      <Column Name="Referee_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Country_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DOB" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FirstName_EN" Type="System.String" DbType="Char(50)" CanBeNull="true" />
      <Column Name="LastName_EN" Type="System.String" DbType="Char(50)" CanBeNull="true" />
      <Association Name="Referee_Match" Member="Matches" ThisKey="Referee_Id" OtherKey="Referee_Id" Type="Match" />
      <Association Name="Country_Referee" Member="Country" ThisKey="Country_Id" OtherKey="Country_ID" Type="Country" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FIFAAssociations" Member="FIFAAssociations">
    <Type Name="FIFAAssociation">
      <Column Name="FIFAAssociation_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FIFAAssociation_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FIFAAssociation_Description" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="FIFAAssociation_Country" Member="Countries" ThisKey="FIFAAssociation_ID" OtherKey="FIFAAssociation_ID" Type="Country" />
    </Type>
  </Table>
  <Table Name="dbo.Players" Member="Players">
    <Type Name="Player">
      <Column Name="Player_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="First_Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Last_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Middle_Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Display_Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DOB" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Height" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Weight" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Country_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="First_Name_Int" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Last_Name_Int" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RequiresReview" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UACity_Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UARegion_Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastUpdate_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NameSearchString" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="Player_PlayerPosition" Member="PlayerPositions" ThisKey="Player_Id" OtherKey="Player_Id" Type="PlayerPosition" />
      <Association Name="Player_MatchLineup" Member="MatchLineups" ThisKey="Player_Id" OtherKey="Player_Id" Type="MatchLineup" />
      <Association Name="Player_MatchEvent" Member="MatchEvents" ThisKey="Player_Id" OtherKey="Player1_Id" Type="MatchEvent" />
      <Association Name="Player_MatchEvent1" Member="MatchEvents1" ThisKey="Player_Id" OtherKey="Player2_Id" Type="MatchEvent" />
      <Association Name="Player_MultimediaTag" Member="MultimediaTags" ThisKey="Player_Id" OtherKey="Player_ID" Type="MultimediaTag" />
      <Association Name="Country_Player" Member="Country" ThisKey="Country_Id" OtherKey="Country_ID" Type="Country" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Competitions" Member="Competitions">
    <Type Name="Competition">
      <Column Name="Competition_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Competition_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CompetitionLevel_Cd" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Competition_Cd" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="Competition_Match" Member="Matches" ThisKey="Competition_Id" OtherKey="Competition_Id" Type="Match" />
    </Type>
  </Table>
  <Table Name="dbo.Coaches" Member="Coaches">
    <Type Name="Coach">
      <Column Name="CoachId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CountryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FirstNameInt" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastNameInt" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DOB" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Coach_MatchLineup" Member="MatchLineups" ThisKey="CoachId" OtherKey="Coach_Id" Type="MatchLineup" />
      <Association Name="Coach_MatchEvent" Member="MatchEvents" ThisKey="CoachId" OtherKey="CoachId" Type="MatchEvent" />
      <Association Name="Coach_MultimediaTag" Member="MultimediaTags" ThisKey="CoachId" OtherKey="CoachId" Type="MultimediaTag" />
      <Association Name="Country_Coach" Member="Country" ThisKey="CountryId" OtherKey="Country_ID" Type="Country" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Matches" Member="Matches">
    <Type Name="Match">
      <Column Name="Match_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HomeClub_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AwayClub_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HomeNationalTeam_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AwayNationalTeam_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HomeScore" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="AwayScore" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="HomePenaltyScore" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="AwayPenaltyScore" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Competition_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CompetitionStage_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Season_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Stadium_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Spectators" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Referee_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Flags" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SpecialNote" Type="System.String" DbType="VarChar(4096)" CanBeNull="true" />
      <Column Name="AdminNotes" Type="System.String" DbType="VarChar(4096)" CanBeNull="true" />
      <Column Name="Sources" Type="System.String" DbType="VarChar(1024)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Match_MatchLineup" Member="MatchLineups" ThisKey="Match_Id" OtherKey="Match_Id" Type="MatchLineup" />
      <Association Name="Match_MatchNote" Member="MatchNotes" ThisKey="Match_Id" OtherKey="Match_Id" Type="MatchNote" />
      <Association Name="Match_MatchEvent" Member="MatchEvents" ThisKey="Match_Id" OtherKey="Match_Id" Type="MatchEvent" />
      <Association Name="Match_MultimediaTag" Member="MultimediaTags" ThisKey="Match_Id" OtherKey="Match_ID" Type="MultimediaTag" />
      <Association Name="Club_Match" Member="Club" ThisKey="HomeClub_Id" OtherKey="Club_ID" Type="Club" IsForeignKey="true" />
      <Association Name="Club_Match1" Member="Club1" ThisKey="AwayClub_Id" OtherKey="Club_ID" Type="Club" IsForeignKey="true" />
      <Association Name="Competition_Match" Member="Competition" ThisKey="Competition_Id" OtherKey="Competition_Id" Type="Competition" IsForeignKey="true" />
      <Association Name="CompetitionStage_Match" Member="CompetitionStage" ThisKey="CompetitionStage_Id" OtherKey="CompetitionStage_ID" Type="CompetitionStage" IsForeignKey="true" />
      <Association Name="NationalTeam_Match" Member="NationalTeam" ThisKey="HomeNationalTeam_Id" OtherKey="NationalTeam_Id" Type="NationalTeam" IsForeignKey="true" />
      <Association Name="NationalTeam_Match1" Member="NationalTeam1" ThisKey="AwayNationalTeam_Id" OtherKey="NationalTeam_Id" Type="NationalTeam" IsForeignKey="true" />
      <Association Name="Referee_Match" Member="Referee" ThisKey="Referee_Id" OtherKey="Referee_Id" Type="Referee" IsForeignKey="true" />
      <Association Name="Season_Match" Member="Season" ThisKey="Season_Id" OtherKey="Season_Id" Type="Season" IsForeignKey="true" />
      <Association Name="Stadium_Match" Member="Stadium" ThisKey="Stadium_Id" OtherKey="Stadium_Id" Type="Stadium" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MatchLineups" Member="MatchLineups">
    <Type Name="MatchLineup">
      <Column Name="MatchLineup_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Player_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ShirtNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsHomeTeamPlayer" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsSubstitute" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Match_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Coach_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Flags" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Coach_MatchLineup" Member="Coach" ThisKey="Coach_Id" OtherKey="CoachId" Type="Coach" IsForeignKey="true" />
      <Association Name="Match_MatchLineup" Member="Match" ThisKey="Match_Id" OtherKey="Match_Id" Type="Match" IsForeignKey="true" />
      <Association Name="Player_MatchLineup" Member="Player" ThisKey="Player_Id" OtherKey="Player_Id" Type="Player" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Seasons" Member="Seasons">
    <Type Name="Season">
      <Column Name="Season_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Season_Description" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CompetitionLevel_Cd" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Season_Cd" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="Season_Match" Member="Matches" ThisKey="Season_Id" OtherKey="Season_Id" Type="Match" />
    </Type>
  </Table>
  <Table Name="dbo.vw_CoachesList" Member="vw_CoachesLists">
    <Type Name="vw_CoachesList">
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CoachId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Country_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="matchesCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_RefereeList" Member="vw_RefereeLists">
    <Type Name="vw_RefereeList">
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Referee_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Country_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="matchesCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Stadiums" Member="Stadiums">
    <Type Name="Stadium">
      <Column Name="Stadium_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Stadium_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Capacity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="City_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Year_Built" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Comments" Type="System.String" DbType="VarChar(1024)" CanBeNull="true" />
      <Column Name="DateAdded" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Stadium_Match" Member="Matches" ThisKey="Stadium_Id" OtherKey="Stadium_Id" Type="Match" />
      <Association Name="City_Stadium" Member="City" ThisKey="City_Id" OtherKey="City_ID" Type="City" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.vwCities" Member="vwCities">
    <Type Name="vwCity">
      <Column Name="City_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="City_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Country_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vwClubs" Member="vwClubs">
    <Type Name="vwClub">
      <Column Name="Club_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Club_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Year_Found" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="City_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="City_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Country_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Multimedia" Member="Multimedias">
    <Type Name="Multimedia">
      <Column Name="Multimedia_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MultimediaType_CD" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="MultimediaSubType_CD" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="FilePath" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FileName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Source" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Author" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Flags" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="DateTaken" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateAdded" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateUpdated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Multimedia_MultimediaTag" Member="MultimediaTags" ThisKey="Multimedia_ID" OtherKey="Multimedia_ID" Type="MultimediaTag" />
    </Type>
  </Table>
  <Table Name="dbo.vGamesByPlayerByTeam" Member="vGamesByPlayerByTeams">
    <Type Name="vGamesByPlayerByTeam">
      <Column Name="First_Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Last_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Display_Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Player_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TotalLIneups" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalMatches" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalMinutes" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsNational" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PlayedFor" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vwMatches" Member="vwMatches">
    <Type Name="vwMatch">
      <Column Name="Match_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Competition_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CompetitionLevel_Cd" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Season_Description" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="HomeScore" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="AwayScore" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="HomePenaltyScore" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="AwayPenaltyScore" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Competition_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CompetitionStage_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Season_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Referee_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Flags" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Stadium_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Spectators" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HomeTeam" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AwayTeam" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HomeTeamCountryCode" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="AwayTeamCountryCode" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="HomeClub_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AwayClub_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HomeNationalTeam_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AwayNationalTeam_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MatchNotes" Member="MatchNotes">
    <Type Name="MatchNote">
      <Column Name="MatchNote_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Match_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="VarChar(2048) NOT NULL" CanBeNull="false" />
      <Association Name="Match_MatchNote" Member="Match" ThisKey="Match_Id" OtherKey="Match_Id" Type="Match" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MatchEvents" Member="MatchEvents">
    <Type Name="MatchEvent">
      <Column Name="MatchEvent_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Event_Cd" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="Minute" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Player1_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Player2_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Match_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EventFlags" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="CoachId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="MatchEvent_MultimediaTag" Member="MultimediaTags" ThisKey="MatchEvent_Id" OtherKey="MatchEvent_ID" Type="MultimediaTag" />
      <Association Name="Coach_MatchEvent" Member="Coach" ThisKey="CoachId" OtherKey="CoachId" Type="Coach" IsForeignKey="true" />
      <Association Name="Match_MatchEvent" Member="Match" ThisKey="Match_Id" OtherKey="Match_Id" Type="Match" IsForeignKey="true" />
      <Association Name="Player_MatchEvent" Member="Player" ThisKey="Player1_Id" OtherKey="Player_Id" Type="Player" IsForeignKey="true" />
      <Association Name="Player_MatchEvent1" Member="Player1" ThisKey="Player2_Id" OtherKey="Player_Id" Type="Player" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MultimediaTags" Member="MultimediaTags">
    <Type Name="MultimediaTag">
      <Column Name="MultimediaTag_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Multimedia_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Player_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Match_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MatchEvent_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Club_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NationalTeam_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CoachId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Club_MultimediaTag" Member="Club" ThisKey="Club_ID" OtherKey="Club_ID" Type="Club" IsForeignKey="true" />
      <Association Name="Coach_MultimediaTag" Member="Coach" ThisKey="CoachId" OtherKey="CoachId" Type="Coach" IsForeignKey="true" />
      <Association Name="Match_MultimediaTag" Member="Match" ThisKey="Match_ID" OtherKey="Match_Id" Type="Match" IsForeignKey="true" />
      <Association Name="MatchEvent_MultimediaTag" Member="MatchEvent" ThisKey="MatchEvent_ID" OtherKey="MatchEvent_Id" Type="MatchEvent" IsForeignKey="true" />
      <Association Name="Multimedia_MultimediaTag" Member="Multimedia" ThisKey="Multimedia_ID" OtherKey="Multimedia_ID" Type="Multimedia" IsForeignKey="true" />
      <Association Name="NationalTeam_MultimediaTag" Member="NationalTeam" ThisKey="NationalTeam_ID" OtherKey="NationalTeam_Id" Type="NationalTeam" IsForeignKey="true" />
      <Association Name="Player_MultimediaTag" Member="Player" ThisKey="Player_ID" OtherKey="Player_Id" Type="Player" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tasks" Member="Tasks">
    <Type Name="Task">
      <Column Name="Task_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Status_CD" Type="System.String" DbType="Char(2) NOT NULL" CanBeNull="false" />
      <Column Name="Type_CD" Type="System.String" DbType="Char(2) NOT NULL" CanBeNull="false" />
      <Column Name="Comments" Type="System.String" DbType="VarChar(5000)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.Player_GetClubs" Method="Player_GetClubs">
    <Parameter Name="PlayerId" Parameter="playerId" Type="System.Int32" DbType="Int" />
    <ElementType Name="Player_GetClubsResult">
      <Column Name="Club" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Club_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>