//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace UaFootball.WebApplication {
    
    
    public partial class Player {
        
        /// <summary>
        /// iPlayerLogo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Image iPlayerLogo;
        
        /// <summary>
        /// mlpLast20 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UaFootball.WebApplication.Controls.MatchLog_Player mlpLast20;
        
        /// <summary>
        /// mlpSBU control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UaFootball.WebApplication.Controls.MatchLog_Player mlpSBU;
        
        /// <summary>
        /// mlpClub control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UaFootball.WebApplication.Controls.MatchLog_Player mlpClub;
    }
}
